version: '3.3'
services:

  # for the hydws service
  hydws:
    image: hydws:1.0 
    env_file:
      - .env
    restart: always
    volumes:
      - type: volume
        source: hydws_log
        target: /var/www/hydws/log
        volume:
          nocopy: false
    ports:
      - "8080:80"

  # for the hydws psql database
  hydws-psql:
    container_name: hydws-psql
    image: postgres:11
    env_file:
      - .env
    restart: always
    volumes:
      - type: volume
        source: hydws_pgdata
        target: /var/lib/postgresql/data
        volume:
          nocopy: false
    ports:
      - "5432:5432"

volumes:
  hydws_log:
  hydws_pgdata:
